### PR TITLE
[Merged by Bors] - updated changelog with removal of PVC-usage documentation

### PR DESCRIPTION
**Pull request by adwk67**
# Description

Updated changelog with removal of PVC-usage documentation

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Reviewer
- [ ] Changelog updated
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
This was only removed from the docs, their was no code in the operator to support the pvcs I guess?

**Comment by adwk67** [comment]
It was done using standard mounts, node selectors etc. and setting an airflow envvar to point at that mount to find the DAGs.

**Comment by adwk67** [comment]
The volume/volumemount fields of the CRD are still there as they can be used for mounting individual DAGs via config maps.

**Review by sbernauer — APPROVED** [review]
Alright, thanks!

**Pull request closed without merging**
