### PR TITLE
[Merged by Bors] - Update to latest stackable images

### PR DESCRIPTION
**Pull request by maltesander**
# Description

- Updated all product / tools images to the latest stackable image version

**DO NOT MERGE BEFORE RELEASE IS DONE!**

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by Maleware** [comment]
At https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/ROOT/examples/example-pvc.yaml at line 27 and 45 there is `docker.stackable.tech/stackable/tools:0.2.0-stackable0` referenced. Should be updated to `docker.stackable.tech/stackable/tools:0.2.0-stackable0.4.0` too I think. 

In https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/ROOT/examples/example-pyspark-pi.yaml at line 9 there is `docker.stackable.tech/stackable/pyspark-k8s:3.3.0-stackable0.1.0` this should be updated to `docker.stackable.tech/stackable/pyspark-k8s:3.3.0-stackable0.3.0`

**Comment by maltesander** [comment]
> At https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/ROOT/examples/example-pvc.yaml at line 27 and 45 there is `docker.stackable.tech/stackable/tools:0.2.0-stackable0` referenced. Should be updated to `docker.stackable.tech/stackable/tools:0.2.0-stackable0.4.0` too I think.
> 
> In https://github.com/stackabletech/airflow-operator/blob/main/docs/modules/ROOT/examples/example-pyspark-pi.yaml at line 9 there is `docker.stackable.tech/stackable/pyspark-k8s:3.3.0-stackable0.1.0` this should be updated to `docker.stackable.tech/stackable/pyspark-k8s:3.3.0-stackable0.3.0`

Good catch! Done https://github.com/stackabletech/airflow-operator/pull/193/commits/19eab3a46e00b416e4f4a8577735c65c78703033

**Review by Maleware — APPROVED** [review]
LGTM

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
