### PR TITLE
Removed AirflowDB

### PR DESCRIPTION
**Pull request by dervoeti**
# Description

Closes https://github.com/stackabletech/airflow-operator/issues/259. As discussed in the issue, the scheduler takes care of the initialization of the database.
 - Removed `.spec.clusterConfig.databaseInitialization` (this was just to enable logging for the database initialization job, which doesn't exist anymore)
 - Removed all the AirflowDB related code
 - Moved database init commands from a separate Job to the command of the scheduler Pod
 - Changed Pod Management Policy to OrderedReady for the scheduler, to make sure multiple scheduler Pods start after another and the init commands don't run in parallel
 - Adjusted the docs. I removed the waiting for the database initialization job and just wrote "After a while, all the Pods in the StatefulSets should be ready". We could also add a wait command for the scheduler here: `kubectl rollout status --watch --timeout=5m statefulset/airflow-scheduler-default` 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [x] (Integration-)Test cases added
- [x] Documentation added or updated
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM! There is still a conflict.

**Comment by dervoeti** [comment]
Thanks for reviewing! Conflict is resolved :)

**Comment by dervoeti** [comment]
We decided we want to move database initialization into a separate Init Container (see https://github.com/stackabletech/superset-operator/issues/404). Will add this to this PR shortly.

**Comment by dervoeti** [comment]
Update: We decided against moving database initialization to an init container, since currently the logs of an init container don't get captured, if the init container fails. Database initialization stays in the scheduler container for now. Also, the CRD change was approved, so this could be merged I'd say.

**Review by maltesander — APPROVED** [review]
LGTM!

**Pull request merged**
