### PR TITLE
Upgrade Vector to version 0.33.0 in the tests

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

* Upgrade Vector to version 0.33.0 in the tests, which is provided by the Vector Helm chart version 0.26.0.
* Fix Clippy warnings

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by maltesander — COMMENTED** [review]
Thanks, must have slipped :)
Can you replace this PR number with (334 i think) the vector update in the changelog?

**Comment by lfrancke** [comment]
Just FYI that 0.33.1 has been released but not saying that we need to upgrade again

**Comment by siegfriedweber** [comment]
> Just FYI that 0.33.1 has been released but not saying that we need to upgrade again

I saw that the new Vector version and the corresponding Helm Chart are available on GitHub but it is not announced yet. However, the actual upgrade has to be done in the Docker image and operator-rs. This PR just fixes the integration tests to be in sync with the version used in the Docker image.

**Review by maltesander — APPROVED** [review]
This is for consistency since i forgot to bump it here. Bumping vector to 0.33.1 is another discussion and should be done in the release issue or in the docker images.

**Comment by siegfriedweber** [comment]
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/110/

**Pull request merged**
