### PR TITLE
Upgrade Vector

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

Make the operator compatible with Vector version 0.31.0

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by siegfriedweber** [comment]
successfully tested:
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/95/

**Comment by razvan** [comment]
The OS test suite is green:
```
--- PASS: kuttl (1187.21s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/smoke_airflow-2.6.1-stackable0.0.0-dev_openshift-true (272.69s)
        --- PASS: kuttl/harness/orphaned-resources_airflow-latest-2.6.1-stackable0.0.0-dev_openshift-true (305.92s)
        --- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.6.1-stackable0.0.0-dev_openshift-true (244.77s)
        --- PASS: kuttl/harness/ldap_airflow-latest-2.6.1-stackable0.0.0-dev_ldap-authentication-server-verification-tls_openshift-true (322.09s)
        --- PASS: kuttl/harness/mount-dags-configmap_airflow-latest-2.6.1-stackable0.0.0-dev_openshift-true (253.70s)
        --- PASS: kuttl/harness/resources_airflow-latest-2.6.1-stackable0.0.0-dev_openshift-true (207.04s)
        --- PASS: kuttl/harness/logging_airflow-2.6.1-stackable0.0.0-dev_openshift-true (227.66s)
        --- PASS: kuttl/harness/cluster-operation_airflow-latest-2.6.1-stackable0.0.0-dev_openshift-true (340.66s)
PASS

```

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by maltesander** [comment]
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/97/

**Pull request merged**
