### PR TITLE
fix/pass gitsync credentials through properly

### PR DESCRIPTION
**Pull request by adwk67**
# Description

fix/pass gitsync credentials through properly

Jenkins: :green_circle:  https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/8/
OKD on replicated: :green_circle: 
```
--- PASS: kuttl (972.27s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/ldap_airflow-latest-2.8.1_ldap-authentication-server-verification-tls_openshift-true_executor-kubernetes (206.21s)
        --- PASS: kuttl/harness/smoke_airflow-2.9.2_openshift-true_executor-kubernetes (270.44s)
        --- PASS: kuttl/harness/resources_airflow-latest-2.8.1_openshift-true (145.02s)
        --- PASS: kuttl/harness/orphaned-resources_airflow-latest-2.8.1_openshift-true (162.93s)
        --- PASS: kuttl/harness/mount-dags-configmap_airflow-latest-2.8.1_openshift-true_executor-kubernetes (145.00s)
        --- PASS: kuttl/harness/cluster-operation_airflow-latest-2.8.1_openshift-true (262.22s)
        --- PASS: kuttl/harness/logging_airflow-2.9.2_openshift-true_executor-kubernetes (479.25s)
        --- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.8.1_openshift-true_executor-kubernetes (205.10s)
```

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Review by razvan — APPROVED** [review]
lgtm!

**Comment by PaulienVa** [comment]
Is this fix available in the nightly build? We are testing it atm and still see the error preventing our statefulsets to start up

**Comment by adwk67** [comment]
Yes, this is in the nightly build which we use for our integration-testing. Please open an issue if something is not working as expected.

**Comment by lfrancke** [comment]
Should this be mentioned in the release notes for 24.11? If so, could you please add a snippet?

**Comment by adwk67** [comment]
@lfrancke sorry for the delay on this. Here, as a comment, or in the changelog?

**Comment by adwk67** [comment]
Here's a snippet for the release notes:

> Fixed in 24.11: in release 24.7 Airflow did not propagate git credentials correctly to the gitsync containers. This has now been corrected and works for both celery- and kubernetes workers.

**Pull request merged**
